on:
  workflow_call:

jobs:
  artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          merge-multiple: true

      - name: Zip up docs
        run: |
          set -vxeuo pipefail
          if [ -d html ]; then
            mv html $GITHUB_REF_NAME
            zip -r docs.zip $GITHUB_REF_NAME
            rm -rf $GITHUB_REF_NAME
          fi

      - name: Create GitHub Release
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
<<<<<<< before updating
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
=======
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
>>>>>>> after updating
        with:
          prerelease: ${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc') }}
          files: "*"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
